presets = {
    "3D Abdomen CT": {
        "confidence": 0.6,
        "iou_threshold": 0.7,
        "max_detections": 15,
        "n_prompts_per_obj": 4,
        "multiprompt_z_spacing": 10,
        "max_z_distance": 20,
        "allow_multiobject_3d": False,
        "predict_all_classes": True,
        "model": "MedSAM2_CTLesion",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "Abdomen"
    },
    "Tooth Segmentation": {
        "confidence": 0.5,
        "iou_threshold": 0.8,
        "max_detections": 20,
        "n_prompts_per_obj": 1,
        "multiprompt_z_spacing": 3,
        "max_z_distance": 3,
        "allow_multiobject_3d": True,
        "predict_all_classes": True,
        "model": "MedSAM2_latest",
        "prompt_model": "YOLOv12-Nano",
        "windowing_preset": "No Windowing"
    },
    "Glioma Segmentation": {
        "confidence": 0.7,
        "iou_threshold": 0.75,
        "max_detections": 5,
        "n_prompts_per_obj": 2,
        "multiprompt_z_spacing": 5,
        "max_z_distance": 10,
        "allow_multiobject_3d": True,
        "predict_all_classes": False,
        "model": "MedSAM2_latest",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "No Windowing"
    },
    "Endoscopy": {
        "confidence": 0.5,
        "iou_threshold": 0.6,
        "max_detections": 10,
        "n_prompts_per_obj": 2,
        "multiprompt_z_spacing": 5,
        "max_z_distance": 8,
        "allow_multiobject_3d": True,
        "predict_all_classes": False,
        "model": "MedSAM2_latest",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "No Windowing"
    },
    "2D CT/MRI Segmentation": {
        "confidence": 0.7,
        "iou_threshold": 0.75,
        "max_detections": 8,
        "n_prompts_per_obj": 1,
        "multiprompt_z_spacing": 15,
        "max_z_distance": 25,
        "allow_multiobject_3d": False,
        "predict_all_classes": True,
        "model": "MedSAM2_CTLesion",
        "prompt_model": "YOLOv12-Nano",
        "windowing_preset": "No Windowing"
    },
    "Laryngeal Endoscopy": {
        "confidence": 0.6,
        "iou_threshold": 0.65,
        "max_detections": 5,
        "n_prompts_per_obj": 4,
        "multiprompt_z_spacing": 4,
        "max_z_distance": 15,
        "allow_multiobject_3d": False,
        "predict_all_classes": False,
        "model": "MedSAM2_latest",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "No Windowing"
    },
    "Skin Lesion Detection": {
        "confidence": 0.6,
        "iou_threshold": 0.8,
        "max_detections": 3,
        "n_prompts_per_obj": 1,
        "multiprompt_z_spacing": 5,
        "max_z_distance": 8,
        "allow_multiobject_3d": False,
        "predict_all_classes": False,
        "model": "MedSAM2_latest",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "No Windowing"
    },
    "Polyp Detection": {
        "confidence": 0.5,
        "iou_threshold": 0.7,
        "max_detections": 15,
        "n_prompts_per_obj": 2,
        "multiprompt_z_spacing": 4,
        "max_z_distance": 6,
        "allow_multiobject_3d": True,
        "predict_all_classes": False,
        "model": "MedSAM2_latest",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "No Windowing"
    },
    "Optic Disk/Cup Segmentation": {
        "confidence": 0.7,
        "iou_threshold": 0.7,
        "max_detections": 2,
        "n_prompts_per_obj": 1,
        "multiprompt_z_spacing": 1,
        "max_z_distance": 1,
        "allow_multiobject_3d": False,
        "predict_all_classes": True,
        "model": "MedSAM2_Latest",
        "prompt_model": "D-FINE-Nano",
        "windowing_preset": "No Windowing"
    }
}